#!/usr/bin/env node
// ============================================================================
//  Record what the analyzer does today, so a rewrite can be checked against it.
//
//  Run this deliberately, never automatically:
//
//      pnpm golden:capture
//
//  It overwrites test/fixtures/golden-path.json with the current analyzer's
//  output. That is the point — and the danger. If test/golden-path.test.mjs is
//  failing, running this makes the failure disappear without fixing anything.
//  Regenerate only when you have decided a behaviour change is correct, and say
//  so in the commit message alongside the diff.
//
//  The baseline exists because "did the TypeScript port change anything?"
//  should be answered by a diff, not a discussion.
// ============================================================================
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

import { AnalysisError, analyzeSpeech, evaluateDefense } from '../apps/web/lib/analyzer.ts';
import {
  ANALYSIS_SCENARIOS,
  DEFENSE_SCENARIOS,
  ERROR_SCENARIOS,
} from '../test/fixtures/golden-scenarios.mjs';

const TARGET = fileURLToPath(new URL('../test/fixtures/golden-path.json', import.meta.url));

function capture() {
  const analyses = ANALYSIS_SCENARIOS.map(({ id, description, ...input }) => ({
    id,
    description,
    input,
    output: analyzeSpeech(input),
  }));

  const defenses = DEFENSE_SCENARIOS.map(({ id, description, answer, criterion }) => ({
    id,
    description,
    input: { answer, criterion },
    output: evaluateDefense({ answer, criterion }),
  }));

  const errors = ERROR_SCENARIOS.map(({ id, input }) => {
    try {
      analyzeSpeech(input);
      throw new Error(`scenario ${id} was expected to fail and did not — INV-7 says invalid input raises`);
    } catch (error) {
      if (!(error instanceof AnalysisError)) throw error;
      return { id, input, error: { code: error.code, message: error.message } };
    }
  });

  return {
    // No timestamp. A regenerated file should diff as "nothing changed" when
    // nothing changed; a clock in the header makes every capture look like one.
    note: 'Generated by scripts/capture-golden.mjs. Do not hand-edit. Regenerating to silence a failing test defeats the purpose.',
    analyses,
    defenses,
    errors,
  };
}

const snapshot = capture();
writeFileSync(TARGET, `${JSON.stringify(snapshot, null, 2)}\n`);
process.stdout.write([
  'golden-capture:',
  '  status: written',
  `  analyses: ${snapshot.analyses.length}`,
  `  defenses: ${snapshot.defenses.length}`,
  `  errors: ${snapshot.errors.length}`,
].join('\n') + '\n');
